CPU: 6
database: '"Rhodophyta"[Organism] AND (latest[filter] AND all[filter] NOT anomalous[filter]))'
models_to_build: ""
models: ["U1", "U2", "U3", "U4", "U5", "U6", "SRP", "MRP"]
extract_genomic_region-length:  "200"
