CPU:  "4"
database: '"Aphidius"[Organism] AND (latest[filter] AND ("chromosome level"[filter] OR "complete genome"[filter]) AND "representative genome"[filter] AND (all[filter] NOT anomalous[filter] AND all[filter] NOT partial[filter]))'
