CPU: 8
database: '"Rhodophyta"[Organism] OR "Haptophyta"[Organism] AND (latest[filter] AND "representative genome"[filter] AND all[filter] NOT anomalous[filter])'
models_to_build: ""
models: ["TRciliates", "TRtracheophyta", "TRvertabrates", "U3", "U6"]
extract_genomic_region-length:  "200"
