database: '"Neuroptera"[Organism] AND (latest[filter] AND "representative genome"[filter] AND all[filter] NOT anomalous[filter])'
extract_genomic_region-length:  200
models: ["U1"]
CPU_for_model_building: 6
